### ISSUE TITLE
Version assertion test always fails

### ISSUE THREAD

**Issue by ctakasakaubc** [brandongk-ubco/gitstats#112]
### This error is received when running Gitstats version 1.0.9 and attempting to generate a repository report.

![image](https://user-images.githubusercontent.com/38474436/97254842-878f1300-17cc-11eb-8cea-6f50f1d98a7e.png)

**Comment by brandongk-ubco** [comment]
It looks like you are running in Jupyter.  Did you try restarting your kernel?

**Comment by ctakasakaubc** [comment]
@brandongk-ubco Yes I restarted the kernel several times, continue to receive the same error.

**Comment by brandongk-ubco** [comment]
When I run it here on a fresh installation, I see:

```(base) ➜  brandongk python ~/work/repos/gitstats/docs/examples/one_week.py
Running with gitstats version: 1.0.9
Group Name: gitstats
Period: 2020-09-09 17:30:00 to 2020-09-16 17:30:00

========================
Individual Contributions
========================
                    user  commits  changes  comments  contributed
0  Brandon Graham-Knight       14      603         1            3

=================
Individual Effort
=================
                    user  commits  changes  comments  contributed  effort
0  Brandon Graham-Knight    125.0    125.0      25.0         75.0    95.0

=============
Issues Closed
=============
   label  completed
0  chore          1
1   task          3

============================================
Issues Ignored Because of Improper Labelling
============================================
None

Team Score: 1

======
Scores
======
                    user  score
0  Brandon Graham-Knight   95.0```

**Comment by brandongk-ubco** [comment]
@ctakasakaubc - I am almost positive it's because the import is being cached in your Python instance.  Restarting the kernel is not the same as refreshing the page.  In Jupyter, there's a `Kernel -> Restart` option.

**Comment by brandongk-ubco** [comment]
![image](https://user-images.githubusercontent.com/69595580/97259110-3c2e3200-17d7-11eb-9e67-4661899d77ad.png)

**Comment by brandongk-ubco** [comment]
@ctakasakaubc - I just ran it again in Syzygy's Jupyter environment, and it worked with no issue for me.  I am now 99% sure it's because you either have the wrong version installed, or (more likely) the correct version installed, but the new version was installed after gitstats was imported... the latter means you keep the old version imported until the Python instance is restarted.

To be sure, run: `print(gitstats.__version__)` and you should see `1.0.9`.

**Comment by ctakasakaubc** [comment]
@brandongk-ubco alright thanks, works now.
