### ISSUE TITLE
github differentiates local machine user and remote repo user

### ISSUE THREAD

**Issue by catsforjodi** [brandongk-ubco/gitstats#113]
Hello sir,

I am writing to you today to let you that when a user pushes from their local machine, GitHub uses a different access token, and therefore differentiates the GitHub account from the local account. As a result, the user shows up twice in gitstats.

**Comment by hnic-dev** [comment]
I have been having the same issue but finally resolved it this week. In my case, my local git user.name was set to my full name. I updated this to my github username and everything is now collected under the github name only.

`git config --global user.name "your-github-username"`

**Comment by catsforjodi** [comment]
@hnic-dev Thank you! That's very helpful. I will do that.
