### ISSUE TITLE
GitStats error: 400 "Returned object contains no URL" 

### ISSUE THREAD

**Issue by RaghavJH** [brandongk-ubco/gitstats#117]
Gitstats version: 1.0.10

Code:

```
!pip uninstall -y gitstats
!pip install --no-cache-dir https://github.com/brandongk-ubco/gitstats/releases/download/v1.0.10/gitstats-1.0.10-py3-none-any.whl
import gitstats
print(gitstats.__version__)
import gitstats
from datetime import datetime

access_token = "CENSORED"
repository = "RaghavJH/Motive"
group_name = "Motive C"

start = datetime.fromisoformat('2020-11-18T18:30')
end = datetime.fromisoformat('2020-12-02T18:30')

stats = gitstats.report(access_token, group_name, repository, start=start, end=end)
print(stats)
```

---------------------------------------------------------------------------
IncompletableObject                       Traceback (most recent call last)
<ipython-input-6-ab6f8f601c25> in <module>
      9 end = datetime.fromisoformat('2020-12-02T18:30')
     10 
---> 11 stats = gitstats.report(access_token, group_name, repository, start=start, end=end)
     12 print(stats)

/opt/conda/lib/python3.8/site-packages/gitstats/__init__.py in report(access_token, group_name, repository, start, end, excluded_users)
     42     report_weeks = getReportWeeks(start, end)
     43     normalizer = AbsoluteEffortWithBonusNormalizer(report_weeks)
---> 44     collector = StatsCollector(repository,
     45                                start=start,
     46                                end=end,

/opt/conda/lib/python3.8/site-packages/gitstats/StatsCollector.py in __init__(self, repository, start, end, excluded_users)
     10         self.end = end
     11         self.excluded_users = excluded_users
---> 12         self._collect()
     13         self._filter()
     14 

/opt/conda/lib/python3.8/site-packages/gitstats/StatsCollector.py in _collect(self)
     26 
     27         self.commits = aggregate_list(
---> 28             [self.repository.getCommitsByPullRequestId(pr) for pr in pr_ids],
     29             columns=[
     30                 "pr", "user", "date", "additions", "deletions", "id", "changes"

/opt/conda/lib/python3.8/site-packages/gitstats/StatsCollector.py in <listcomp>(.0)
     26 
     27         self.commits = aggregate_list(
---> 28             [self.repository.getCommitsByPullRequestId(pr) for pr in pr_ids],
     29             columns=[
     30                 "pr", "user", "date", "additions", "deletions", "id", "changes"

/opt/conda/lib/python3.8/site-packages/gitstats/GithubAPIRepository.py in getCommitsByPullRequestId(self, id)
     82                 {
     83                     "pr": int(pr.number),
---> 84                     "user": GithubAPIRepository.resolve_author(commit),
     85                     "date": date,
     86                     "additions": commit.stats.additions,

/opt/conda/lib/python3.8/site-packages/gitstats/GithubAPIRepository.py in resolve_author(commit)
     61             return commit.commit.raw_data["author"]["name"]
     62         else:
---> 63             return commit.author.name if commit.author.name else commit.author.login
     64 
     65     def getCommitsByPullRequestId(self, id):

/opt/conda/lib/python3.8/site-packages/github/NamedUser.py in name(self)
    276         :type: string
    277         """
--> 278         self._completeIfNotSet(self._name)
    279         return self._name.value
    280 

/opt/conda/lib/python3.8/site-packages/github/GithubObject.py in _completeIfNotSet(self, value)
    297     def _completeIfNotSet(self, value):
    298         if value is NotSet:
--> 299             self._completeIfNeeded()
    300 
    301     def _completeIfNeeded(self):

/opt/conda/lib/python3.8/site-packages/github/GithubObject.py in _completeIfNeeded(self)
    301     def _completeIfNeeded(self):
    302         if not self.__completed:
--> 303             self.__complete()
    304 
    305     def __complete(self):

/opt/conda/lib/python3.8/site-packages/github/GithubObject.py in __complete(self)
    305     def __complete(self):
    306         if self._url.value is None:
--> 307             raise GithubException.IncompletableObject(
    308                 400, "Returned object contains no URL"
    309             )

IncompletableObject: 400 "Returned object contains no URL"

**Comment by brandongk-ubco** [comment]
@RaghavJH - This looks like an issue with the author set on the commit.  It's failing here: https://github.com/brandongk-ubco/gitstats/blob/43387742a3d3bf9a2585e6e04c20416c11b226b9/gitstats/GithubAPIRepository.py#L63

I can wrap it in a try / except to ignore the commit pretty easily, but I want to make sure it's not something strange going on with GitHub that it would be masking.  Can you please let me know:

- If you have tried running it again to rule out any transient errors in the API.
- I have heard that it works for one week (25 to 02) however, not for 2 weeks (18 to 02) .  Have you run it from the 18 to 25?  Does it work?
- I would assume it's limited to a single commit causing the issue, likely with the author being different than the others and causing this error.  Can you look at the git log from all commits from the 18 to 25 and let me know if any authors look out of place?

BGK

**Comment by RaghavJH** [comment]
Hey Brandon, think I found it. One of my teammates said his GitHub desktop was being weird, and his commits are showing as unverified and that there is no associated e-mail with his user:

![Screenshot_1](https://user-images.githubusercontent.com/23582295/101235730-71df0880-36fd-11eb-9bc0-ea79aef832d8.png)
![Screenshot_2](https://user-images.githubusercontent.com/23582295/101235729-70addb80-36fd-11eb-8c23-d1bd5b358f0c.png)

How do we go about this? Thanks!

**Comment by brandongk-ubco** [comment]
Hi @RaghavJH - You should be able to rebase to correct any author problems: 

git commit --amend --author="Author Name <email@address.com>" --no-edit

From: https://stackoverflow.com/questions/3042437/how-to-change-the-commit-author-for-one-specific-commit

I think the only way we could fix it in gitstats would be to catch the error and ignore the commit entirely, which would mask similar issues for future users.
