### ISSUE TITLE
Ran into RateLimitExceededException

### ISSUE THREAD

**Issue by catsforjodi** [brandongk-ubco/gitstats#119]
Hi, 

I tried to run gitstats today, and ran into a RateLimitExceededException. I don't know what to do.

**Comment by catsforjodi** [comment]
I am not DOSing, I promise. :)

**Comment by brandongk-ubco** [comment]
Hi @catsforjodi - This is an error that comes from GitHub's API rate limitations.  Did you run the report with a long reporting time, or run several reports in quick succession?

Regardless, unless you've made many changes recently this should go away the next time you run the report.  If not, try waiting a bit and reducing the report duration.

I think the only solution we could implement in gitstats is a backoff between requests... hopefully this is not needed for you to get your report to run.

**Comment by catsforjodi** [comment]
Thank you! This is very helpful information. I wanted a few hours and ran it again. It works now.
