### ISSUE TITLE
Meeting about GitStats and marking for course

### ISSUE THREAD

**Issue by merelister** [brandongk-ubco/gitstats#93]
Hi Brandon! We've scheduled a meeting with Dr Hui for Tuesday (October 20) at 2pm to discuss GitStats. We'd appreciate your perspective in discussing normalizing effort scores, constraints with the GitHub API, etc. Are you available to meet with us sometime before 2pm on Tuesday?

**Comment by brandongk-ubco** [comment]
Hi @merelister - I am always happy to discuss potential use cases.  Unfortunately, I am not available Tuesday at 2PM, but I can meet up this weekend or Monday afternoon.

For the normalizing scores, we are making the change described in #94 to handle large differences in Changes through a non-linear function.

As far as the GitHub API goes, we have access to everything here: https://docs.github.com/en/free-pro-team@latest/rest that is implemented in https://github.com/PyGithub/PyGithub - if you take a read through those docs, you should start to get an understanding of what is possible.  Keep in mind that the system also needs to be explainable, so it's better to have general rules that are easily communicated than a bunch of specific rules dealing with uncommon edge cases.

If you have any specific issues or, preferably, well-worked suggestions, please log them here as issues.

**Comment by merelister** [comment]
Hi @brandongk-ubco, thanks for the quick response and updates! I've been reading through suggestions from my peers but as I'm sure you're very aware it's difficult to translate a lot of the ideas into solutions. I'll try to keep the suggestions organized to existing issues as much as possible.
