### ISSUE TITLE
Compression formula for Changes

### ISSUE THREAD

**Issue by brandongk-ubco** [brandongk-ubco/gitstats#94]
Before normalizing, run Changes through a non-linear function to better handle extra-large cases.  Function below.

![image](https://user-images.githubusercontent.com/69595580/96325274-58fa8680-0fdb-11eb-833d-c26c0594a892.png)

**Comment by brandongk-ubco** [comment]
Equation:

y = 1.557803 + (−0.01363552 − 1.557803)/(1 + (x/266.8213)

**Comment by brandongk-ubco** [comment]
This is now resolved and released in v1.0.6.  I had to make a minor change to the function to make the y-intercept 0.  I also capped the maximum changes at 5000.  Assuming someone in your group achieved the maximum, you would get the following marks for your change amounts:

changes, change_score_percentage

1000, 83.35
500, 68.77
250, 50.78
100, 28.26
50, 16.15
0,0

**Comment by brandongk-ubco** [comment]
@mjcrouse
@zamora-UBC

**Comment by mjcrouse** [comment]
What are the thoughts on the 5000 max? Where does that come from? This seems pretty high still. For a student project anyway where we are being expected to work ~6-10 hours per week.

I think a better solution to the capping is doing a per commit cap. Something like if a commit is > 500 lines it doesn't count at all towards changes(this would probably be my preference), or is reduced down to 500 lines. The goal here is really to avoid the auto-generated code type changes or uploading of non-code files that get counted.

PS. I thought I had said it already (maybe it's in another thread) but my first thought about this was non-linear LoC changes (and potentially non-linear commits as well) so I'm a big fan of the change overall.

**Comment by brandongk-ubco** [comment]
@mjcrouse - We tried to avoid non-linear functions because it makes changes to already-generated reports harder...  There was an assumption that people would not be re-linting all of their code or committing large binaries into git on a regular basis, but there were enough examples that this was re-considered.  The exact formula came from Dr. Hui, but I believe the reasoning was that 1000 lines was probably a good guess of a reasonable cap produced by a single person in a single week; this value was set to 1.  I also believe there have been cases in the past of people working extremely hard and producing more than 1000 lines in a week, and those are recognized by allowing the scale to go to 5000.  This is what I understood, but you'd have to ask Dr. Hui to be certain...

If you suggest changing the formula or adding non-linearity to other parts of the function, feel free to open another issue for discussion.
